---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ovog

<!-- badges: start -->
<!-- badges: end -->

The goal of {ovog} is to read in the hafvog's json files that are inside the hafvog zip-dump into R.

## Installation

You can install the development version of ovog from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
remotes::install_github("einarhjorleifsson/ovog")
```

## The fundamental stuff

With {ovog} you can read in the content of the hafvog zip files via:

```{r example}
library(ovog)
zip_path <- system.file("zips", "A3-2024.zip", package = "ovog")
tmpfile <- tempfile()
download.file("ftp://ftp.hafro.is/pub/data/A7-2024.zip", destfile = tmpfile)
zip_path <- c(zip_path, tmpfile)
d <- hv_read_zips(zip_path, collapse_station = TRUE)

names(d)

d$stodvar |> 
  dplyr::left_join(d$skraning) |> 
  dplyr::glimpse()

d |> 
  hv_create_tables() |> 
  names()
```
