devtools::check()
devtools::build_readme()
pkgdown::build_site()
# system("mkdir /net/hafri.hafro.is/export//hhomeafr/ieinarhj/public_html/pkg/osmx")
system("rm -rf  /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/osmx/*")
system("cp -r docs/* /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/osmx/.")
system("chmod -R a+rX /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/osmx")
