devtools::check()
devtools::build_readme()
pkgdown::build_site()
system("rm -rf  /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pgk/ovog/*")
system("cp -r docs/* /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ovog/.")
system("chmod -R a+rX /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ovog")
