---
title: "Hafvog json files"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## To read

```{r setup}
library(mardata)
library(tidyverse)
#library(hafvog)
library(devtools)
load_all()
res <- read_rds("C:/Users/einarhj/Desktop/SMX/data2/res.rds")
```

```{r}
maeliadgerd <- 
  res$other.stuff$aid |> 
  arrange(aid) |> 
  mutate(adgerd = iconv(adgerd, from = "ISO-8859-1", to = "UTF-8")) |> 
  select(maeliadgerd = aid, adgerd) |> 
  mutate(ag = c("length", "length-sex", "age", "n_length", "n", "shrimp", "skjóða",
                "diet", "diet-normal", "diet-luxury", "tagging", "rubbish", "weight"))
```

```{r}
pth <- "C:/Users/einarhj/Desktop/hafvog/inst/extdata/B4-2022"
st <- hv_station(pth)
st |> glimpse()
```


## Emulating "numer"-table

Imagine we are doing survey B4-2022 (just because I have the zip file)

```{r}
pth <- system.file("extdata", "B4-2022", package = "hafvog")
dir(pth)
m <- 
  hv_measures(pth, std = FALSE)
msummary <- 
  m |> 
  group_by(synis_id, maeliadgerd) |> 
  summarise(rows = n(),
            fjoldi = sum(fjoldi, na.rm = TRUE),
            .groups = "drop") |> 
  left_join(maeliadgerd) |> 
  arrange(synis_id, maeliadgerd)
msummary |> 
  select(.sid = synis_id, adgerd, fjoldi) |> 
  pivot_wider(names_from = adgerd, values_from = fjoldi) |> 
  knitr::kable()
  
```

```{r}
# Stoðtöflur

magaastand <-
  
```

```{r}
# predator
pred <- 
  m |>
  dplyr::filter(!is.na(magaastand)) |>
  count(maeliadgerd)
  dplyr::select(synis_id, pred = tegund, nr, oslaegt, slaegt, 
            astand = magaastand) |> 
  dplyr::left_join(tbl_xe(con, "hafvog.magaastand") |>  
                     dplyr::select(astand, lysing_astands), 
                   by = "astand") |> 
  dplyr::select(-astand) |> 
  dplyr::rename(astand = lysing_astands)
```


```{r, eval = FALSE}
# Opening zip file example
zip_path <- system.file("extdata", "TB1-2022.zip", package = "hafvog")
tmpdir <- tempdir()
unzip(zipfile = zip_path, exdir = tmpdir)
hv_cruise(tmpdir)
hv_station(tmpdir) |> dplyr::glimpse()
hv_towstations(tmpdir) |> dplyr::glimpse()
hv_environment(tmpdir) |> dplyr::glimpse()
hv_measures(tmpdir) |> dplyr::glimpse()
```

## Station table

```{r}
pth <- system.file("extdata", "B4-2022", package = "hafvog")
dir(pth)

st <- hv_station(pth, std = FALSE)
st |> glimpse()
st2 <- hv_towstations(pth, std = FALSE)
st2 |> glimpse()
st3 <- hv_environment(pth, std = FALSE)
st3 |> glimpse()
st <- 
  st |> 
  left_join(st2) |> 
  left_join(st3)
st |> glimpse()
```

## Emulating numer

```{r}
m <- 
  hv_me
```


## Downstream considerations

Need to read the json stuff and then emulate some additional downstream code in order to prepare for the smx-app

### Lesa stodvar

```{r}
# xe::lesa_stodvar
tbl_xe(con, paste0(schema, ".stodvar")) %>%
  dplyr::select(synis_id:heildarafli, synaflokkur, fishing_gear_no) %>%
  dplyr::mutate(ar = to_number(to_char(dags, "YYYY")),
                veidarfaeri = ifelse(is.na(veidarfaeri),
                                     fishing_gear_no,
                                     veidarfaeri)) %>%
  dplyr::left_join(tbl_xe(con, paste0(schema, ".togstodvar")) %>%
                     dplyr::select(synis_id:eykt), by = "synis_id") %>%
  dplyr::left_join(tbl_xe(con, paste0(schema, ".umhverfi")) %>%
                     dplyr::select(synis_id:sjondypi), by = "synis_id") %>%
  dplyr::mutate(synis_id = ifelse(schema == "fiskar", synis_id, -synis_id),
                index = reitur * 100 + tognumer)
```

```{r, echo = FALSE}
# the code inside import_hafvog
# Main data from hafvog ------------------------------------------------------
i <- 1


st <-
  lesa_stodvar(con, schema[i]) %>%
  dplyr::filter(synaflokkur %in% id)

# if(st %>% dplyr::count() %>% dplyr::collect() == 0) {
#   stop("There is no data for specified 'synaflokkur'")
# }

st <-
  st %>%
  dplyr::filter(ar == now.year)

nu.list[[i]] <-
  st %>%
  dplyr::select(synis_id) %>%
  dplyr::left_join(lesa_numer(con, schema[i]), by = "synis_id") %>%
  dplyr::select(synis_id, tegund, fj_maelt, fj_talid, fj_alls) %>%
  dplyr::collect(n = Inf) %>%
  dplyr::filter(!is.na(tegund))

le.list[[i]] <-
  st %>%
  dplyr::select(synis_id) %>%
  dplyr::left_join(lesa_lengdir(con, schema[i]) %>%
                     dplyr::group_by(synis_id, tegund, lengd) %>%
                     dplyr::summarise(fjoldi = sum(fjoldi, na.rm = TRUE)) %>%
                     dplyr::ungroup(), by = "synis_id") %>%
  dplyr::collect(n = Inf)  %>%
  dplyr::filter(!is.na(tegund))

kv.list[[i]] <-
  st %>%
  dplyr::select(synis_id) %>%
  dplyr::left_join(lesa_kvarnir(con, schema[i]), by = "synis_id") %>%
  dplyr::collect(n = Inf)

st.list[[i]] <-
  st %>%
  dplyr::collect(n = Inf) %>%
  dplyr::mutate(lon1 = -kastad_v_lengd,
                lat1 = kastad_n_breidd,
                lon2 = -hift_v_lengd,
                lat2 = hift_n_breidd) %>%
  geo::geoconvert(col.names = c("lat1", "lon1")) %>%
  geo::geoconvert(col.names = c("lat2", "lon2")) %>%
  dplyr::mutate(lon = (lon1 + lon2) / 2,
                lat = (lat1 + lat2) / 2,
                toglengd = ifelse(is.na(toglengd), 4, toglengd))

skraning <-
  tbl_xe(con, "hafvog.stodvar") %>%
  dplyr::select(synis_id:heildarafli, synaflokkur) %>%
  dplyr::mutate(ar = to_number(to_char(dags, "YYYY"))) %>%
  dplyr::left_join(tbl_xe(con, "hafvog.togstodvar") %>%
                     dplyr::select(synis_id:eykt), by = "synis_id") %>%
  dplyr::left_join(tbl_xe(con, "hafvog.umhverfi") %>%
                     dplyr::select(synis_id:sjondypi), by = "synis_id") %>%
  dplyr::mutate(index = reitur * 100 + tognumer) %>%
  dplyr::filter(synaflokkur %in% id,
                ar == now.year) %>%
  dplyr::select(synis_id) %>%
  dplyr::left_join(tbl_xe(con, "hafvog.skraning"),
                   by = "synis_id") %>%
  dplyr::collect(n = Inf) %>%
  dplyr::mutate(synis_id = -synis_id)

# ----------------------------------------------------------------------------
# Other stuff needed from hafvog
# B. STADLAR -----------------------------------------------------------------

stadlar.rallstodvar <-
  lesa_stadla_rallstodvar(con) %>%
  dplyr::filter(synaflokkur %in% id) %>%
  dplyr::collect(n = Inf) %>%
  # 2023-09-30 Quick fix
  dplyr::filter(!is.na(hift_v)) |>
  # fix an error in hift_v for SMH, should be corrected in database
  dplyr::mutate(hift_v = ifelse(hift_v == -2444550, -244455, hift_v)) %>%
  dplyr::mutate(hift_n = ifelse(hift_n ==  6537038,  653703, hift_n)) %>%
  geo::geoconvert(col.names = c("kastad_v", "kastad_n")) %>%
  geo::geoconvert(col.names = c("hift_v",   "hift_n"))

lid <- stadlar.rallstodvar$leidangur_id[[1]]
stadlar.tegundir <-
  lesa_stadla_tegund_smb(con) %>%
  dplyr::filter(leidangur_id == lid) %>%
  dplyr::arrange(tegund) %>%
  dplyr::collect(n = Inf) %>%
  tidyr::gather(variable, value, lifur_low:kynkirtlar_high) %>%
  dplyr::mutate(value = value / 100) %>%
  tidyr::spread(variable, value)

stadlar.lw <-
  lesa_stadla_lw(con) %>%
  dplyr::collect(n = Inf) %>%
  dplyr::mutate(osl1 = osl * (1 - fravik),
                osl2 = osl * (1 + fravik),
                sl1 = sl * (1 - fravik),
                sl2 = sl * (1 + fravik)) %>%
  dplyr::select(tegund, lengd, osl1:sl2)

fisktegundir <-
  #tbl_xe(con, "hafvog.fisktegundir") %>%
  tbl_xe(con, "hafvog.species_v") %>%
  dplyr::select(tegund = species_no, heiti = name) %>%
  dplyr::arrange(tegund) %>%
  dplyr::collect(n = Inf)

aid <-
  tbl_xe(con, "hafvog.maeliatridi") %>%
  dplyr::collect() %>%
  dplyr::rename(aid = id, adgerd = heiti) %>%
  dplyr::collect(n = Inf)
sid <-
  #tbl_xe(con, "hafvog.fisktegundir") %>%
  tbl_xe(con, "hafvog.species_v") %>%
  dplyr::select(sid = species_no, tegund = name) %>%
  dplyr::arrange(tegund) %>%
  dplyr::collect(n = Inf)
prey_names <-
  #tbl_xe(con, "hafvog.f_tegundir") %>%
  tbl_xe(con, "hafvog.species_v") %>%
  dplyr::select(faeduhopur = food_no, lat_heiti = sci_name,
                isl_heiti = name,
                tegund = species_no) %>%
  dplyr::collect(n = Inf)


pred <-
  hv_pred(con) %>%
  dplyr::collect(n = Inf)
prey <-
  hv_prey(con) %>%
  dplyr::collect(n = Inf)

other.stuff <- list(stadlar.rallstodvar = stadlar.rallstodvar,
                    stadlar.tegundir = stadlar.tegundir,
                    stadlar.lw = stadlar.lw,
                    fisktegundir = fisktegundir,
                    aid = aid,
                    sid = sid,
                    prey_names = prey_names,
                    prey = prey,
                    pred = pred)



ret <- list(st = st, nu = nu, le = le, kv = kv, skraning = skraning,
            other.stuff = other.stuff)

if(!dir.exists("data2")) dir.create("data2")
# Timabundið skítamix
xe::tbl_xe(con, "hafvog.maeliatridi") %>%
  dplyr::collect() %>%
  dplyr::select(maeliadgerd = id, heiti) %>%
  readr::write_rds("data2/maeliatridi.rds")


if(store) {
  
  if(!dir.exists("data2")) dir.create("data2")
  ret %>% readr::write_rds(path = "data2/hafvog.rds")
}

return(ret)
```

